import type { NextPage } from 'next';
import Head from 'next/head';

const Login: NextPage = () => {
  return (
    <>
      <Head>
        <title>Objective | Login</title>
        {/* <meta name='description' content='Generated by create-t3-app' /> */}
        {/* <link rel='icon' href='/favicon.ico' /> */}
      </Head>
      <div>Login Page</div>
    </>
  );
};

export default Login;
