import type { NextPage } from 'next';
import Head from 'next/head';

const Notifications: NextPage = () => {
  return (
    <>
      <Head>
        <title>Objective | Notifications</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>Notifications Page</div>
    </>
  )
}

export default Notifications