import type { NextPage } from 'next';
import Head from 'next/head';

const Search: NextPage = () => {
  return (
    <>
      <Head>
        <title>Objective | Search</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>Search Page</div>
    </>
  )
}

export default Search
