import type { NextPage } from 'next';
import type { ReactElement } from 'react'
import Head from 'next/head';
import Link from 'next/link';

const SignUp = () => {
  return (
    <>
      <Head>
        <title>SignUp</title>
        {/* <meta name='description' content='Generated by create-t3-app' /> */}
        {/* <link rel='icon' href='/favicon.ico' /> */}
      </Head>
      {/* Create a signup page with formik */}
      <main className='container max-w-screen-lg mx-auto flex flex-col'>

        <h1>Welcome Back</h1>
        <p> Give the people what they want. </p>

        <button>
          <Link href='/login'>
            Log In
          </Link>
        </button>

        <button>
          <Link href='/signup'>
            Sign Up
          </Link>
        </button>
      </main>
       

    </>
  );
};

// render without a layout
SignUp.getLayout = (page: ReactElement) => page;

export default SignUp;
